// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwp2rsSrPrZs6HkSgUanjEfXhQjRBP5hM',
    appId: '1:1294281324:android:dcbbe7143de21e740b4649',
    messagingSenderId: '1294281324',
    projectId: 'test-230711-d942d',
    databaseURL: 'https://test-230711-d942d-default-rtdb.firebaseio.com',
    storageBucket: 'test-230711-d942d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZnzs3jCWvBEfYxKksD1LtP9umMs46coA',
    appId: '1:1294281324:ios:ce5e2f951865dc180b4649',
    messagingSenderId: '1294281324',
    projectId: 'test-230711-d942d',
    databaseURL: 'https://test-230711-d942d-default-rtdb.firebaseio.com',
    storageBucket: 'test-230711-d942d.appspot.com',
    iosClientId: '1294281324-ut296b8jkbvaj1n9qnujidsfn5r55jgc.apps.googleusercontent.com',
    iosBundleId: 'com.vladih.computervision.flutterVisionExample',
  );
}
